# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
